### ISSUE TITLE
Any way to renable the tooltips after calling tips.destroy()?

### ISSUE THREAD

**Issue by Dillybob92** [darsain/tooltips#10]
I want to destroy all tooltips and then re-enable them all without refreshing the page. Is this possible?

For example, calling tips.destroy() works, but when tips.reload doesn't, because they are destroyed. Or is there anyway to hide or remove all tooltips on the page without just hiding them CSS? (And no not toggling).

**Comment by Dillybob92** [comment]
The only reason I ask this is because I found a small, VERY small bug with my inventory system with items. And if you click just fast enough, and hove your mouse over another item, the tooltip will stay displayed.  I can do tips.reload() after each item is placed down in the inventory, and it fixes it. But, I want to disable all tooltips when the user is moving a specific item instead, then just renable the tooltips after an item is placed.

**Comment by darsain** [comment]
This is how I do it in my Twitch Giveaways app: [src/js/component/tga.js#L254](https://github.com/darsain/twitch-giveaways/blob/master/src/js/component/tga.js#L254)

Line 255 calls `makeTooltips` whenever config `displayTooltips` changes.
Line 256 is the initial `makeTooltips` call.

As you can see I'm just creating anew Tooltips instance when previous got destroyed. The destroy method semantics are the same in all languages: the object has been destroyed, it's gone, and can't be used again. Just because we can bastardize this in JavaScript doesn't mean we should.
